name: tiny_ecs
description: A minimal, functional Entity Component System (ECS) for applications that need to manage complex entities with dynamic component sets
version: 0.4.5
homepage: https://github.com/vento007/tiny_ecs
repository: https://github.com/vento007/tiny_ecs

topics:
  - ecs
  - entity-component-system
  - game-engine
  - architecture
  - data-processing

environment:
  sdk: ^3.0.0

dev_dependencies:
  test: ^1.21.0
  lints: ^3.0.0

 
flutter:

 